nav:
  - Home: index.md
  - Classes:
    - Upper School:
        - Computational Thinking: ct.md
        - Intro to CS: intro.md
        - APCS: apcs.md
        - Data Structures and Algorithms: datastructures.md
    - Middle School:
        - CoderZ: coderz.md
        - CodeCombat: codecombat.md
  - Tutorials:
      - Vim: vim.md
      - Unix shell: shell.md
  - Coding Games:
      - Battlesnake: battlesnake.md
      - CodinGame: codingame.md
  - Languages:
      - Java: java.md
  - Software:
      - IDEs:
          - VSCode: https://code.visualstudio.com/download
          - IntelliJ: https://www.jetbrains.com/idea/download/
          - PyCharm: https://www.jetbrains.com/pycharm/download
      - Colab: colab.md
      - Git: git.md
      - Jupyter: jupyter.md
      - Jupyter Options: jupyter-options.md
      - MkDocs: mkdocs.md
      - Markdown: markdown.md
  - Hardware:
      - Circuit Playground: cpx.md
      - Crickit/CPX: cricket.md
  - Online Curriculum:
      - Nand2Tetris: nand2tetris.md
      - Coding Resources: coding-resources.md
  - Advice: advice.md
  - Interesting: interesting.md
  - Hour of Code: hoc.md
  - Teaching CS: teaching.md
  - Athenian Websites:
      - Programming Tutorials: https://github.com/athenian-programming
      - Athenian FLL: https://www.athenian-fll.org
      - Athenian FRC: https://www.athenian-robotics.org

theme:
  name: 'material'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/owls.jpg'
  favicon: 'assets/images/favicon.ico'

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics: ['UA-156755533-1', 'auto']

site_name: Athenian Computer Science
site_url: https://www.athenian-cs.org
site_description: Athenian CS Documentation
site_author: Athenian CS Team

repo_url: https://github.com/athenian-computational-thinking/athenian-cs-mkdocs
repo_name: 'Athenian CS Home'